-- BIONANO MEGA-AUTHORITY CONTENT - PARTE 2 DE 3 (ES/EN)
-- Artículos: 005 (Export UE), 006 (Hospital), 007 (Water), 008 (Residual Effect)

SET NAMES utf8mb4;

INSERT INTO blog_posts (id, slug, status, author, cover_image, type, category_name, created_at) VALUES
('blog-005', 'exportacion-ue-residuo-cero-estandar', 'published', 'Consultoría BioNano', 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=2000', 'article', 'Sostenibilidad', '2026-04-09 16:45:00'),
('blog-006', 'bioseguridad-hospitalaria-nanociencia-avanzada', 'published', 'Dr. Roberto Gomez', 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2000', 'article', 'Industria y Salud', '2026-04-11 08:00:00'),
('blog-007', 'ahorro-agua-limpieza-industrial-sostenible', 'published', 'Ing. Sostenibilidad', 'https://images.unsplash.com/photo-1581093196277-9f608009874e?q=80&w=2000', 'article', 'Sostenibilidad', '2026-04-13 12:00:00'),
('blog-008', 'efecto-residual-persistencia-nanotecnologica', 'published', 'Ing. Carlos Mendoza', 'https://images.unsplash.com/photo-1504198453319-5ce911baf2ef?q=80&w=2000', 'article', 'Industria y Salud', '2026-04-15 10:30:00')
ON DUPLICATE KEY UPDATE status = VALUES(status), author = VALUES(author), cover_image = VALUES(cover_image), category_name = VALUES(category_name);

-- TRADUCCIONES DETALLADAS 005-008
INSERT INTO blog_post_translations (post_id, language, title, excerpt, content, meta_title, meta_description) VALUES
('blog-005', 'es', 'Exportación UE: El camino hacia el cumplimiento del Residuo Cero', 'Asegura tus envíos al mercado europeo mediante tecnologías que eliminan la residualidad química.', '[{"id":"1","type":"rich-text","content":{"html":"<h2>Entrar en mercados premium</h2><p>La UE exige cada vez más pureza. BioNano permite proteger el fruto durante el trayecto marítimo sin generar trazas medibles en destino.</p>"}}]', 'Exportar a la UE con BioNano', 'Lidera la exportación de residuo cero con tecnología nano.'),
('blog-005', 'en', 'EU Export: The Path to Zero Residue Compliance', 'Secure your shipments to the European market through technologies that eliminate chemical residue.', '[{"id":"1","type":"rich-text","content":{"html":"<h2>Entering Premium Markets</h2><p>The EU demands increasing purity. BioNano allows fruit protection during sea travel without generating measurable traces at the destination.</p>"}}]', 'Export to EU with BioNano', 'Lead zero-residue export with nano technology.'),

('blog-006', 'es', 'Bioseguridad Hospitalaria: Superficies que se desinfectan solas', 'Cómo reducir las infecciones nosocomiales con capas de Zinc que no se evaporan.', '[{"id":"1","type":"rich-text","content":{"html":"<h2>Protección continua</h2><p>BioNano crea un escudo persistente en equipos médicos y áreas comunes, reduciendo drásticamente la transmisión bacteriana cruzada.</p>"}}]', 'Sanidad Hospitalaria Nano | BioNano', 'Mejora la bioseguridad clínica con BioNano.'),
('blog-006', 'en', 'Hospital Biosecurity: Surfaces that Self-Disinfect', 'How to reduce nosocomial infections with Zinc layers that do not evaporate.', '[{"id":"1","type":"rich-text","content":{"html":"<h2>Continuous Protection</h2><p>BioNano creates a persistent shield on medical equipment and common areas, drastically reducing cross-bacterial transmission.</p>"}}]', 'Nano Hospital Health | BioNano', 'Improve clinical biosecurity with BioNano.'),

('blog-007', 'es', 'Sostenibilidad Hídrica: Menos Agua, Más Higiene Industrial', 'Optimiza los ciclos de limpieza y reduce la huella hídrica con la eficiencia de BioNano.', '[{"id":"1","type":"rich-text","content":{"html":"<h2>Optimización de recursos</h2><p>Nuestras nanopartículas requieren menos enjuague, permitiendo ahorrar hasta un 30% del volumen de agua en limpiezas profundas.</p>"}}]', 'Ahorro de Agua con BioNano', 'Sostenibilidad y ahorro hídrico industrial.'),
('blog-007', 'en', 'Water Sustainability: Less Water, More Industrial Hygiene', 'Optimize cleaning cycles and reduce water footprint with BioNano efficiency.', '[{"id":"1","type":"rich-text","content":{"html":"<h2>Resource Optimization</h2><p>Our nanoparticles require less rinsing, allowing you to save up to 30% of water volume in deep cleaning.</p>"}}]', 'Water Saving with BioNano', 'Sustainability and industrial water saving.'),

('blog-008', 'es', 'El Efecto Residual: La Clave de la Persistencia Nanotecnológica', 'Entiende por qué la protección de días es superior a la desinfección de segundos.', '[{"id":"1","type":"rich-text","content":{"html":"<h2>Blindaje nanométrico</h2><p>Mientras el cloro desaparece en segundos, BioNano permanece activo protegiendo la superficie contra la recontaminación constante.</p>"}}]', 'Persistencia Nano | BioNano', 'Descubre el poder del efecto residual de BioNano.'),
('blog-008', 'en', 'The Residual Effect: The Key to Nanotechnological Persistence', 'Understand why day-long protection is superior to second-long disinfection.', '[{"id":"1","type":"rich-text","content":{"html":"<h2>Nanometric Shielding</h2><p>While chlorine disappears in seconds, BioNano remains active protecting the surface against constant recontamination.</p>"}}]', 'Nano Persistence | BioNano', 'Discover the power of BioNano\'s residual effect.')
ON DUPLICATE KEY UPDATE title = VALUES(title), excerpt = VALUES(excerpt), content = VALUES(content);
